services:
  - type: web
    name: cafe-rodante-nfc
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn cafe_rodante.wsgi"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: "*"
